// export const API_URLS = 'http://humanitydemo.rubrutech.com/';
export const API_URLS = 'https://humanity.rubrutech.com/';

export const stateList = [
    {name: 'Aasam', id: 1},
    {name: 'Andhra Pardesh', id: 2},
    {name: 'Bihar', id: 3},
    {name: 'Canada', id: 3},
    {name: 'Chandigarh', id: 3},
    {name: 'Chattisgarh', id: 3},
    {name: 'Delhi', id: 3},
    {name: 'Gujrat', id: 3},
    {name: 'Hryana', id: 3},
    {name: 'Himachal Pardesh', id: 3},
    {name: 'Jammu & Kashmir', id: 3},
    {name: 'Jharkhand', id: 3},
    {name: 'Karnataka', id: 3},
    {name: 'Kerala', id: 3},
    {name: 'Madhya Pardesh', id: 3},
    {name: 'Maharashtra', id: 3},
    {name: 'Manipur', id: 3},
    {name: 'Meghalaya', id: 3},
    {name: 'Mizoram', id: 3},
    {name: 'Nagaland', id: 3},
    {name: 'Nepal', id: 3},
    {name: 'Orissa', id: 3},
    {name: 'Punjab', id: 3},
    {name: 'Qatar', id: 3},
    {name: 'Rajasthan', id: 3},
    {name: 'Sikkim', id: 3},
    {name: 'Tamilnadu', id: 3},
    {name: 'Telangana', id: 3},
    {name: 'Tripura', id: 3},
    {name: 'Uttar Pardesh', id: 3},
    {name: 'Uttarakhand', id: 3},
    {name: 'West Bengal', id: 3},
]